# -*- coding: utf-8 -*-
"""stroke_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pMe9iIP7fKr9Bz9-AE63OD8Z7y9NgrpB
"""

import streamlit as st
import pandas as pd
import numpy as np
import tensorflow as tf
import pickle
import os
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

st.set_page_config(
    page_title="Stroke Risk Dashboard",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded"
)

@st.cache_data
def load_data():
    df = pd.read_csv("stroke_dataset_cleaned_final.csv")
    return df

df = load_data()

# ====================================================================
# 🛠️ [SISI AI ENGINEER] LANGKAH 1: MEMUAT ASSET NEURAL NETWORK
# ====================================================================
@st.cache_resource  # Mencegah web lemot karena me-load ulang model terus-menerus
def load_stroke_ai_assets():
    model_path = 'models/saved_model/stroke_prediction_model'
    scaler_path = 'models/scaler.pkl'
    encoder_path = 'models/label_encoders.pkl'
    
    # Keras 3 / TF 2.21+ menggunakan TFSMLayer untuk memuat format SavedModel lama
    model = tf.keras.layers.TFSMLayer(model_path, call_endpoint='serving_default')
    
    # Load Preprocessing Tools
    with open(scaler_path, 'rb') as f:
        scaler = pickle.load(f)
    with open(encoder_path, 'rb') as f:
        label_encoders = pickle.load(f)
        
    return model, scaler, label_encoders

# Panggil komponen ke memori dashboard
try:
    model, scaler, label_encoders = load_stroke_ai_assets()
except Exception as e:
    st.error(f"⚠️ Gagal memuat komponen AI. Periksa struktur folder 'models/'. Error: {e}")

# ====================================================================

st.sidebar.image("https://img.icons8.com/color/96/brain.png", width=80)
st.sidebar.title("🧠 Stroke Risk Dashboard")
st.sidebar.markdown("---")

menu = st.sidebar.radio(
    "Navigasi",
    [
        "📊 Overview",
        "🔍 EDA & Distribusi",
        "⚠️ Faktor Risiko",
        "🧪 A/B Testing",
        "🤖 Prediksi Stroke",
        "📋 Kesimpulan"
    ]
)

st.sidebar.markdown("---")
st.sidebar.markdown(f"**Total Data:** {len(df):,} baris")
st.sidebar.markdown(f"**Fitur:** {df.shape[1]} kolom")
stroke_pct = df['stroke'].mean() * 100
st.sidebar.markdown(f"**Prevalensi Stroke:** {stroke_pct:.1f}%")

STROKE_COLOR = {"0": "#4A90D9", "1": "#E74C3C", 0: "#4A90D9", 1: "#E74C3C"}

def stroke_label(x):
    return "Stroke" if x == 1 else "Tidak Stroke"

df["stroke_label"] = df["stroke"].apply(stroke_label)

# ══════════════════════════════════════════════════════════════════════════════
# PAGE 1: OVERVIEW
# ══════════════════════════════════════════════════════════════════════════════
if menu == "📊 Overview":
    st.title("📊 Overview Dataset Stroke Prediction")
    st.markdown("Dataset: **Stroke Prediction Dataset** (Kaggle - fedesoriano) | Sudah melalui proses Data Wrangling")
    st.markdown("---")

    # KPI Cards
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Pasien", f"{len(df):,}")
    col2.metric("Kasus Stroke", f"{df['stroke'].sum():,}", f"{stroke_pct:.1f}% dari total")
    col3.metric("Rata-rata Usia", f"{df['age'].mean():.0f} tahun")
    col4.metric("Rata-rata BMI", f"{df['bmi'].mean():.1f}")

    st.markdown("---")

    # Distribusi Stroke
    col_a, col_b = st.columns(2)

    with col_a:
        st.subheader("Distribusi Kasus Stroke")
        stroke_counts = df['stroke_label'].value_counts().reset_index()
        stroke_counts.columns = ['Status', 'Jumlah']
        fig = px.pie(stroke_counts, values='Jumlah', names='Status',
                     color='Status',
                     color_discrete_map={"Stroke": "#E74C3C", "Tidak Stroke": "#4A90D9"},
                     hole=0.4)
        fig.update_layout(height=350)
        st.plotly_chart(fig, use_container_width=True)

    with col_b:
        st.subheader("Informasi Dataset")
        st.dataframe(
            pd.DataFrame({
                "Kolom": df.columns,
                "Tipe Data": df.dtypes.values,
                "Null": df.isnull().sum().values,
                "Unik": df.nunique().values
            }),
            use_container_width=True,
            height=350
        )

    st.markdown("---")
    st.subheader("Preview Data (5 baris pertama)")
    st.dataframe(df.drop(columns=['stroke_label']).head(), use_container_width=True)

    st.markdown("---")
    st.subheader("📖 Data Dictionary")
    dict_data = {
        'Fitur': ['gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
                  'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
                  'smoking_status', 'stroke'],
        'Tipe': ['Kategorikal', 'Numerik', 'Biner', 'Biner', 'Kategorikal',
                 'Kategorikal', 'Kategorikal', 'Numerik', 'Numerik',
                 'Kategorikal', 'Biner (Target)'],
        'Deskripsi': [
            'Jenis kelamin pasien',
            'Usia pasien dalam tahun',
            '1 = memiliki hipertensi, 0 = tidak',
            '1 = memiliki penyakit jantung, 0 = tidak',
            'Status pernikahan',
            'Jenis pekerjaan pasien',
            'Tipe tempat tinggal pasien',
            'Rata-rata kadar glukosa dalam darah',
            'Body Mass Index — indeks massa tubuh',
            'Status merokok pasien',
            '1 = pernah stroke, 0 = tidak (variabel target)'
        ],
        'Nilai / Rentang': [
            'Male, Female',
            '0 – 82 tahun',
            '0, 1',
            '0, 1',
            'Yes, No',
            'Private, Self-employed, Govt_job, children, Never_worked',
            'Urban, Rural',
            '55.12 – 271.74 mg/dL',
            '10.3 – 97.6',
            'formerly smoked, never smoked, smokes, Unknown',
            '0, 1'
        ]
    }
    st.dataframe(pd.DataFrame(dict_data), use_container_width=True, hide_index=True)

# ══════════════════════════════════════════════════════════════════════════════
# PAGE 2: EDA & DISTRIBUSI
# ══════════════════════════════════════════════════════════════════════════════
elif menu == "🔍 EDA & Distribusi":
    st.title("🔍 Exploratory Data Analysis")
    st.markdown("---")

    tab1, tab2, tab3 = st.tabs(["📈 Variabel Numerik", "🏷️ Variabel Kategorikal", "🔥 Korelasi"])

    with tab1:
        st.subheader("Distribusi Variabel Numerik berdasarkan Status Stroke")
        num_cols = ['age', 'avg_glucose_level', 'bmi']
        labels = {'age': 'Usia', 'avg_glucose_level': 'Rata-rata Kadar Glukosa', 'bmi': 'BMI'}

        for col in num_cols:
            fig = px.histogram(df, x=col, color='stroke_label', barmode='overlay',
                               nbins=40,
                               color_discrete_map={"Stroke": "#E74C3C", "Tidak Stroke": "#4A90D9"},
                               labels={col: labels[col], 'stroke_label': 'Status'},
                               title=f"Distribusi {labels[col]}")
            fig.update_layout(height=320, bargap=0.05)
            st.plotly_chart(fig, use_container_width=True)

        st.subheader("Boxplot Perbandingan Statistik")
        col_sel = st.selectbox("Pilih variabel:", num_cols,
                               format_func=lambda x: labels[x])
        fig = px.box(df, x='stroke_label', y=col_sel, color='stroke_label',
                     color_discrete_map={"Stroke": "#E74C3C", "Tidak Stroke": "#4A90D9"},
                     labels={col_sel: labels[col_sel], 'stroke_label': 'Status'},
                     title=f"Boxplot {labels[col_sel]}")
        st.plotly_chart(fig, use_container_width=True)

    with tab2:
        st.subheader("Distribusi Variabel Kategorikal berdasarkan Status Stroke")
        cat_cols = ['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status']
        labels_cat = {
            'gender': 'Jenis Kelamin', 'ever_married': 'Status Menikah',
            'work_type': 'Jenis Pekerjaan', 'Residence_type': 'Tipe Tempat Tinggal',
            'smoking_status': 'Status Merokok'
        }

        for col in cat_cols:
            grp = df.groupby([col, 'stroke_label']).size().reset_index(name='count')
            fig = px.bar(grp, x=col, y='count', color='stroke_label', barmode='group',
                         color_discrete_map={"Stroke": "#E74C3C", "Tidak Stroke": "#4A90D9"},
                         labels={'count': 'Jumlah', col: labels_cat[col], 'stroke_label': 'Status'},
                         title=f"Distribusi {labels_cat[col]}")
            fig.update_layout(height=320)
            st.plotly_chart(fig, use_container_width=True)

    with tab3:
        st.subheader("Heatmap Korelasi Antar Variabel Numerik")
        num_df = df[['age', 'avg_glucose_level', 'bmi', 'hypertension', 'heart_disease', 'stroke']]
        corr = num_df.corr()

        fig, ax = plt.subplots(figsize=(8, 6))
        sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm",
                    linewidths=0.5, ax=ax, vmin=-1, vmax=1)
        ax.set_title("Heatmap Korelasi", fontsize=14, fontweight='bold')
        st.pyplot(fig)

        st.markdown("**Insight:** Variabel `age` memiliki korelasi tertinggi dengan `stroke`, diikuti `hypertension` and `avg_glucose_level`.")

# ══════════════════════════════════════════════════════════════════════════════
# PAGE 3: FAKTOR RISIKO
# ══════════════════════════════════════════════════════════════════════════════
elif menu == "⚠️ Faktor Risiko":
    st.title("⚠️ Analisis Faktor Risiko Stroke")
    st.markdown("---")

    st.subheader("1. Segmentasi Kelompok Usia terhadap Risiko Stroke")
    bins = [0, 18, 35, 50, 65, 100]
    labels_age = ['0-18', '19-35', '36-50', '51-65', '65+']
    df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels_age, right=False)

    df["health_risk_score"] = df["hypertension"] + df["heart_disease"]
    df["glucose_bmi_risk"] = df["avg_glucose_level"] * df["bmi"]

    st.markdown("---")
    st.subheader("Feature Engineering")
    st.dataframe(df[["age", "age_group", "health_risk_score", "glucose_bmi_risk"]].head(10))

    age_stroke = df.groupby(['age_group', 'stroke_label']).size().reset_index(name='count')
    fig = px.bar(age_stroke, x='age_group', y='count', color='stroke_label', barmode='group',
                 color_discrete_map={"Stroke": "#E74C3C", "Tidak Stroke": "#4A90D9"},
                 labels={'count': 'Jumlah', 'age_group': 'Kelompok Usia', 'stroke_label': 'Status'},
                 title="Distribusi Stroke per Kelompok Usia")
    st.plotly_chart(fig, use_container_width=True)

    st.subheader("2. Rata-rata Kadar Glukosa per Faktor Risiko")
    cat_sel = st.selectbox("Pilih faktor:", ['work_type', 'smoking_status', 'ever_married', 'gender'],
                           format_func=lambda x: {
                               'work_type': 'Jenis Pekerjaan', 'smoking_status': 'Status Merokok',
                               'ever_married': 'Status Menikah', 'gender': 'Jenis Kelamin'
                           }[x])
    glc = df.groupby([cat_sel, 'stroke_label'])['avg_glucose_level'].mean().reset_index()
    fig = px.bar(glc, x=cat_sel, y='avg_glucose_level', color='stroke_label', barmode='group',
                 color_discrete_map={"Stroke": "#E74C3C", "Tidak Stroke": "#4A90D9"},
                 labels={'avg_glucose_level': 'Rata-rata Kadar Glukosa', 'stroke_label': 'Status'},
                 title=f"Rata-rata Kadar Glukosa berdasarkan {cat_sel}")
    st.plotly_chart(fig, use_container_width=True)

    st.subheader("3. Pengaruh Hipertensi & Penyakit Jantung")
    col1, col2 = st.columns(2)

    with col1:
        ht = df.groupby(['hypertension', 'stroke_label']).size().reset_index(name='count')
        ht['hypertension'] = ht['hypertension'].map({0: 'Tidak', 1: 'Ya'})
        fig = px.bar(ht, x='hypertension', y='count', color='stroke_label', barmode='group',
                     color_discrete_map={"Stroke": "#E74C3C", "Tidak Stroke": "#4A90D9"},
                     title="Hipertensi vs Stroke",
                     labels={'hypertension': 'Hipertensi', 'count': 'Jumlah', 'stroke_label': 'Status'})
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        hd = df.groupby(['heart_disease', 'stroke_label']).size().reset_index(name='count')
        hd['heart_disease'] = hd['heart_disease'].map({0: 'Tidak', 1: 'Ya'})
        fig = px.bar(hd, x='heart_disease', y='count', color='stroke_label', barmode='group',
                     color_discrete_map={"Stroke": "#E74C3C", "Tidak Stroke": "#4A90D9"},
                     title="Penyakit Jantung vs Stroke",
                     labels={'heart_disease': 'Penyakit Jantung', 'count': 'Jumlah', 'stroke_label': 'Status'})
        st.plotly_chart(fig, use_container_width=True)

    st.subheader("4. Scatter Plot: Usia vs Kadar Glukosa")
    fig = px.scatter(df, x='age', y='avg_glucose_level', color='stroke_label',
                     color_discrete_map={"Stroke": "#E74C3C", "Tidak Stroke": "#4A90D9"},
                     opacity=0.6, size_max=6,
                     labels={'age': 'Usia', 'avg_glucose_level': 'Kadar Glukosa', 'stroke_label': 'Status'},
                     title="Hubungan Usia dan Kadar Glukosa terhadap Risiko Stroke")
    st.plotly_chart(fig, use_container_width=True)

# ══════════════════════════════════════════════════════════════════════════════
# PAGE 4: A/B TESTING
# ══════════════════════════════════════════════════════════════════════════════
elif menu == "🧪 A/B Testing":
    st.title("🧪 Implementasi A/B Testing")
    st.markdown("Pengujian dilakukan untuk melihat apakah terdapat hubungan yang signifikan antara hipertensi dan kejadian stroke.")

    from scipy.stats import chi2_contingency
    contingency = pd.crosstab(df["hypertension"], df["stroke"])

    st.subheader("Tabel Kontingensi")
    st.dataframe(contingency)

    chi2, p, dof, expected = chi2_contingency(contingency)
    col1, col2 = st.columns(2)
    col1.metric("Chi-Square", round(chi2, 3))
    col2.metric("P-Value", round(p, 6))

    if p < 0.05:
        st.success("Terdapat hubungan signifikan antara hipertensi dan stroke.")
    else:
        st.warning("Tidak terdapat hubungan signifikan.")

    st.markdown("""
    **Hipotesis**
    - H0 : Tidak ada hubungan hipertensi dengan stroke
    - H1 : Ada hubungan hipertensi dengan stroke
    """)

# ══════════════════════════════════════════════════════════════════════════════
# PAGE 5: PREDIKSI STROKE [MODIFIKASI TOTAL AI ENGINEER - COMPATIBLE WITH KERAS 3]
# ══════════════════════════════════════════════════════════════════════════════
elif menu == "🤖 Prediksi Stroke":
    st.title("🤖 Prediksi Risiko Stroke dengan Neural Network (95%)")
    st.markdown("Silakan isi indikator klinis di bawah ini untuk menguji risiko stroke pasien.")
    st.markdown("---")

    # Layout Form dibagi menjadi 2 Kolom agar rapi
    f_col1, f_col2 = st.columns(2)

    with f_col1:
        gender = st.selectbox("Jenis Kelamin (gender)", ["Male", "Female"])
        age = st.slider("Usia (age)", 0, 100, 45)
        hypertension = st.selectbox("Memiliki Hipertensi? (hypertension)", [0, 1], format_func=lambda x: "Ya (1)" if x==1 else "Tidak (0)")
        heart_disease = st.selectbox("Memiliki Penyakit Jantung? (heart_disease)", [0, 1], format_func=lambda x: "Ya (1)" if x==1 else "Tidak (0)")
        ever_married = st.selectbox("Pernah Menikah? (ever_married)", ["Yes", "No"])

    with f_col2:
        work_type = st.selectbox("Jenis Pekerjaan (work_type)", ["Private", "Self-employed", "Govt_job", "children", "Never_worked"])
        Residence_type = st.selectbox("Tipe Tempat Tinggal (Residence_type)", ["Urban", "Rural"])
        glucose = st.number_input("Rata-rata Kadar Glukosa (avg_glucose_level)", 50.0, 300.0, 105.0)
        bmi = st.number_input("Indeks Massa Tubuh / BMI", 10.0, 100.0, 28.0)
        smoking_status = st.selectbox("Status Merokok (smoking_status)", ["never smoked", "formerly smoked", "smokes", "Unknown"])

    st.markdown("---")
    
    if st.button("🔥 Jalankan Prediksi AI"):
        # 1. Bungkus input user ke dalam Dataframe sesuai skema pelatihan data di Colab
        raw_input = pd.DataFrame([{
            'gender': gender,
            'age': age,
            'hypertension': hypertension,
            'heart_disease': heart_disease,
            'ever_married': ever_married,
            'work_type': work_type,
            'Residence_type': Residence_type,
            'avg_glucose_level': glucose,
            'bmi': bmi,
            'smoking_status': smoking_status
        }])
        
        # 2. Preprocessing Data Kategorikal Menggunakan label_encoders.pkl
        categorical_cols = ['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status']
        for col in categorical_cols:
            le = label_encoders[col]
            raw_input[col] = le.transform(raw_input[col])
            
        # 3. Preprocessing Data Numerik Menggunakan scaler.pkl
        numeric_cols = ['age', 'avg_glucose_level', 'bmi']
        raw_input[numeric_cols] = scaler.transform(raw_input[numeric_cols])
        
        # 4. Tembak Data Hasil Preprocessing ke Model Neural Network (Adaptasi Fungsional Keras 3)
        # Memanggil layer secara langsung karena TFSMLayer tidak memiliki method .predict()
        predictions = model(raw_input)
        
        # Ekstrak nilai tensor dari output dictionary TFSMLayer secara aman
        if isinstance(predictions, dict):
            first_key = list(predictions.keys())[0]
            prediction_score = float(predictions[first_key][0][0].numpy())
        else:
            prediction_score = float(predictions[0][0].numpy())
        
       # 5. Tampilkan Visualisasi Hasil Output Kece ke Dashboard
        st.subheader("📊 Hasil Analisis Kecerdasan Buatan (AI):")
        
        # Membuat visual meteran probabilitas sederhana menggunakan widget metric
        col_res1, col_res2 = st.columns([1, 2])
        
        # Hitung nilai persentase asli untuk mempermudah logika coding
        percentage_score = prediction_score * 100
        
        with col_res1:
            st.metric(label="Probabilitas Risiko", value=f"{percentage_score:.2f}%")
            
        with col_res2:
            # Menggunakan skala persentase langsung (0% - 100%) agar sensitif dan akurat
            if percentage_score >= 20.0:
                st.error(f"⚠️ **PERINGATAN:** Pasien terindikasi memiliki potensi **RISIKO TINGGI** terkena stroke ({percentage_score:.2f}%). Segera lakukan pemeriksaan klinis mendalam!")
            elif 0.50 <= percentage_score < 20.0:
                st.warning(f"⚡ **WASPADA:** Pasien masuk dalam kategori **RISIKO SEDANG** ({percentage_score:.2f}%). Disarankan untuk mengevaluasi pola makan dan mengontrol tekanan darah.")
            else:
                st.success(f"✅ **AMAN:** Pasien dikategorikan memiliki risiko stroke yang **RENDAH** ({percentage_score:.2f}%). Tetap jaga pola hidup sehat!")
# ══════════════════════════════════════════════════════════════════════════════
# PAGE 6: KESIMPULAN
# ══════════════════════════════════════════════════════════════════════════════
if menu == "📋 Kesimpulan":
    st.title("📋 Kesimpulan & Insight")
    st.markdown("---")

    insights = [
        ("🔴", "Usia adalah faktor risiko terkuat",
         "Pasien stroke rata-rata berusia lebih tua (~68 tahun) dibanding yang tidak stroke (~41 tahun). Risiko meningkat signifikan pada kelompok usia 51-65 dan 65+."),
        ("🟠", "Kadar glukosa tinggi meningkatkan risiko",
         "Pasien stroke memiliki rata-rata kadar glukosa lebih tinggi (~133 mg/dL) dibanding yang tidak stroke (~103 mg/dL). Kelompok dengan glukosa >125 mg/dL perlu perhatian khusus."),
        ("🟡", "Hipertensi berkontribusi signifikan",
         "Proporsi hipertensi pada pasien stroke (26.5%) jauh lebih tinggi dibanding yang tidak stroke (9.5%), menunjukkan korelasi yang kuat."),
        ("🟢", "Penyakit jantung memperparah risiko",
         "Pasien dengan riwayat penyakit jantung memiliki kemungkinan stroke yang lebih tinggi, meski prevalensinya relatif kecil dalam dataset."),
        ("🔵", "BMI berperan namun tidak dominan",
         "Rata-rata BMI pasien stroke sedikit lebih tinggi, namun perbedaannya tidak sebesar variabel usia atau glukosa."),
        ("🟣", "Status merokok dan pekerjaan berpengaruh",
         "Kelompok 'formerly smoked' dan 'Private worker' memiliki proporsi stroke lebih tinggi, kemungkinan terkait faktor usia yang lebih tua dalam kelompok tersebut."),
    ]

    for icon, title, desc in insights:
        with st.expander(f"{icon} {title}", expanded=True):
            st.write(desc)

    st.markdown("---")
    st.subheader("📌 Rekomendasi")
    st.markdown("""
    1. **Skrining rutin** untuk populasi usia >50 tahun, terutama yang memiliki hipertensi atau penyakit jantung.
    2. **Pengelolaan kadar glukosa** sebagai langkah pencegahan stroke, khususnya pada penderita diabetes.
    3. **Gaya hidup sehat** (berhenti merokok, menjaga BMI ideal) untuk mengurangi faktor risiko yang dapat dikontrol.
    4. **Model prediktif** menggunakan fitur: `age`, `avg_glucose_level`, `bmi`, `hypertension`, `heart_disease` sebagai fitur utama.
    """)

    st.markdown("---")
    st.caption("Dashboard dibuat untuk keperluan analisis data proyek Data Science | Stroke Prediction Dataset (Kaggle - fedesoriano)")